fetch_weather/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('history', views.past, name='history'),
    path('', views.home, name='home'),
    path('units/', views.select_units, name='units'),
    path('add_card/', views.add_card, name='add_card'),
    path('sort/', views.sort, name='sort'),
    path('remove_card/', views.remove_card, name='remove_card'),
    path('update_card/', views.update_card, name='update_card'),
]

weather_history/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('fetch_weather.urls'))
]

fetch_weather/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.constraints import UniqueConstraint

class Location(models.Model):
    loc = models.CharField(max_length=100)
    datetimeEpoch = models.DateTimeField()
    temp = models.FloatField()
    feelslike = models.FloatField()
    humidity = models.FloatField()
    precip = models.FloatField()
    snow = models.FloatField()
    preciptype = models.CharField(max_length=50, null=True, blank=True)
    pressure = models.FloatField()
    cloudcover = models.FloatField()
    uvindex = models.FloatField()
    conditions = models.CharField(max_length=50)
    icon = models.CharField(max_length=30)
    sunrise = models.CharField(max_length=30)
    sunset = models.CharField(max_length=30)
    moonphase = models.FloatField()
    daily_description = models.TextField()
    last_modified = models.DateTimeField(auto_now=True)
    order = models.SmallIntegerField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    session = models.TextField()
    tz_display_dt = models.CharField(max_length=30)
    tz_display_lm = models.CharField(max_length=30)
    pretty_loc = models.CharField(max_length=100)

    class Meta:
        unique_together = ['loc', 'author', 'session']
        ordering = ['order']

users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserPreferences(models.Model):
    units = models.CharField(max_length=10, default='us')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    session = models.TextField()

fetch_weather/forms.py
from django.forms import ModelForm
from .models import Location

class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = ['loc', 'datetimeEpoch', 'temp', 'feelslike', 'humidity', 'precip',
        'snow', 'preciptype', 'pressure', 'cloudcover', 'uvindex', 'conditions', 'icon',
        'sunrise', 'sunset', 'moonphase', 'daily_description', 'order', 'author', 'session',
        'tz_display_dt', 'tz_display_lm', 'pretty_loc']

fetch_weather/views.py
from django.shortcuts import render, redirect
from django_htmx.http import HttpResponseClientRefresh
from django.contrib import messages
from django.http import HttpResponse
from fetch_weather.forms import LocationForm
from geopy.geocoders import Nominatim
import json
import requests
from pathlib import Path
import environ
import os
from .models import Location
from users.forms import UserPreferencesForm
from users.models import UserPreferences
from django.db.models import Q, Count
import datetime, time
import re
from django.utils import timezone


BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
API_KEY = env('API_KEY')

METRIC_UNITS = {'temp_unit': '°C', 'precip_unit': 'mm', 'snow_unit': 'cm',
                'wind_unit': 'km/h', 'visibility_unit': 'km', 'pressure_unit': 'mb'}
UK_UNITS = {'temp_unit': '°C', 'precip_unit': 'mm', 'snow_unit': 'cm',
            'wind_unit': 'mph', 'visibility_unit': 'miles', 'pressure_unit': 'mb'}
US_UNITS = {'temp_unit': '°F', 'precip_unit': 'in', 'snow_unit': 'in',
            'wind_unit': 'mph', 'visibility_unit': 'miles', 'pressure_unit': 'mb'}

def home(request):
    context = {}
    if request.user.is_authenticated:
        UserPreferences.objects.filter(author=None, session=request.session.session_key).update(author=request.user)
        UserPreferences.objects.filter(author=request.user).exclude(session=request.session.session_key).delete()
        user_prefs, created = UserPreferences.objects.get_or_create(author=request.user,
            defaults={'units': 'us','author': request.user, 'session': request.session.session_key})
        units = user_prefs.units
        Location.objects.filter(session=request.session.session_key, author=None).update(author=request.user)
        duplicates = Location.objects.filter(author=request.user).values('loc').annotate(records=Count('loc')).filter(records__gt=1)
        if duplicates:
            Location.objects.filter(author=request.user, loc=duplicates[0]['loc']).exclude(session=request.session.session_key).delete()
        locations = list(Location.objects.filter(author=request.user).all().values())

        if units == 'metric':
            front_units = METRIC_UNITS
        elif units == 'uk':
            front_units = UK_UNITS 
        elif units == 'us':
            front_units = US_UNITS
        cards = {}
        for loc in locations:
            if units == 'us':
                loc['temp'] = round((float(loc['temp'])*1.8)+32, 1)
                loc['feelslike'] = round((float(loc['feelslike'])*1.8)+32, 1)
                loc['precip'] = round(float(loc['precip'])*25.4, 1)
                loc['snow'] = round(float(loc['snow'])*2.54, 1)
            cards[loc['loc']] = loc
        if not cards:
            context = {}
        else:
            context = {'saved_locs': cards, 'front_units': front_units}
    else:
        if not request.session.session_key:
            request.session.create()

        user_prefs, _ = UserPreferences.objects.get_or_create(session=request.session.session_key,
            defaults={'units': 'us', 'author': None, 'session': request.session.session_key})
        units = user_prefs.units
        request.session['units'] = user_prefs.units
        locations = list(Location.objects.filter(session=request.session.session_key).all().values())
        
        if units == 'metric':
            front_units = METRIC_UNITS
        elif units == 'uk':
            front_units = UK_UNITS
        elif units == 'us':
            front_units = US_UNITS
        cards = {}
        for loc in locations:
            if units == 'us':
                loc['temp'] = round((float(loc['temp'])*1.8)+32, 1)
                loc['feelslike'] = round((float(loc['feelslike'])*1.8)+32, 1)
                loc['precip'] = round(float(loc['precip'])*25.4, 1)
                loc['snow'] = round(float(loc['snow'])*2.54, 1)
            cards[loc['loc']] = loc

        context = {'saved_locs': cards, 'front_units': front_units}

    return render(request, 'fetch_weather/home.html', context)


def select_units(request):
    request_unit = request.GET.get('units')
    if request.user.is_authenticated:
        user_prefs, _ = UserPreferences.objects.get_or_create(author=request.user,
            defaults={'units': 'us', 'author': request.user, 'session': request.session.session_key})
        unit_from_db = UserPreferences.objects.filter(author=request.user).first()
        valid_units = {'metric': 'Metric', 'us': 'US', 'uk': 'UK'}
        if request_unit not in valid_units:
            return HttpResponseClientRefresh()
        locations = list(Location.objects.filter(author=request.user).all().values())
        
        if request_unit in valid_units:
            if request_unit == 'metric':
                units = METRIC_UNITS
                unit_from_db.units = 'metric'
            elif request_unit == 'uk':
                units = UK_UNITS
                unit_from_db.units = 'uk'
            elif request_unit == 'us':
                units = US_UNITS
                unit_from_db.units = 'us'
            unit_from_db.save()
            cards = {}
            for loc in locations:
                if request_unit == 'us':
                    loc['temp'] = round((float(loc['temp'])*1.8)+32, 1)
                    loc['feelslike'] = round((float(loc['feelslike'])*1.8)+32, 1)
                    loc['precip'] = round(float(loc['precip'])*25.4, 1)
                    loc['snow'] = round(float(loc['snow'])*2.54, 1)
                cards[loc['loc']] = loc
        else:
            context = {}
            units = {}
        context = {'saved_locs': cards, 'units': units}

    else:
        user_prefs, _ = UserPreferences.objects.get_or_create(session=request.session.session_key,
            defaults={'units': 'us', 'author': None,
            'session': request.session.session_key})
        unit_from_db = UserPreferences.objects.filter(session=request.session.session_key).first()
        valid_units = {'metric': 'Metric', 'us': 'US', 'uk': 'UK'}
        locations = list(Location.objects.filter(session=request.session.session_key).all().values())
        
        if request_unit in valid_units:
            cards = {}
            if request_unit == 'metric':
                units = METRIC_UNITS
                unit_from_db.units = 'metric'
            elif request_unit == 'uk':
                units = UK_UNITS
                unit_from_db.units = 'uk'
            elif request_unit == 'us':
                units = US_UNITS
                unit_from_db.units = 'us'
            unit_from_db.save()
            for loc in locations:
                if request_unit == 'us':
                    loc['temp'] = round((float(loc['temp'])*1.8)+32, 1)
                    loc['feelslike'] = round((float(loc['feelslike'])*1.8)+32, 1)
                    loc['precip'] = round(float(loc['precip'])*25.4, 1)
                    loc['snow'] = round(float(loc['snow'])*2.54, 1)
                cards[loc['loc']] = loc
        else:
            context = {}
        request.session['units'] = unit_from_db.units
        context = {'saved_locs': cards, 'units': units}
        
    return render(request, 'fetch_weather/partials/units.html', context)


def add_card(request):
    context = {}
    try:
        max_order_num = Location.objects.filter(author=request.user).last().order + 1
    except:
        max_order_num = 1
    
    location = request.POST.get('location')
    if location.isspace() or location == '':
        response = HttpResponse(status=204)
        response['HX-Trigger'] = json.dumps({'showMessage': [{"message": 'Please input a location.',
            "color": "bg-danger-subtle", "title": "Error"}]})
        return response
    geolocator = Nominatim(user_agent='http')
    location_validated = geolocator.geocode(location, addressdetails=True, language='en')
    if not location_validated:
        response = HttpResponse(status=204)
        response['HX-Trigger'] = json.dumps({'showMessage': [{"message": 'Please input a valid location.',
            "color": "bg-danger-subtle", "title": "Error"}]})
        return response

    if 'city' in str(location_validated.raw['address']):
        city = str(location_validated.raw['address']['city'])
    elif 'town' in str(location_validated.raw['address']):
        city = str(location_validated.raw['address']['town'])
    elif 'village' in str(location_validated.raw['address']):
        city = str(location_validated.raw['address']['village'])
    elif 'county' in str(location_validated.raw['address']):
        city = str(location_validated.raw['address']['county'])
    elif 'province' in str(location_validated.raw['address']):
        city = str(location_validated.raw['address']['province'])
    else:
        city = ''
    state = str(
        location_validated.raw['address']['state']) if 'state' in str(
        location_validated.raw['address']) else ''
    country = str(
        location_validated.raw['address']['country']) if 'country' in str(
        location_validated.raw['address']) else ''
    if state == city:
        frontend_location = ', '.join([city, country])
    elif city == '':
        frontend_location = ', '.join([state, country])
    elif state == '':
        frontend_location = ', '.join([city, country])
    elif state == '' and city == '':
        frontend_location = country
    else:
        frontend_location = ', '.join([city, state, country])

    url = (
        f'https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/{frontend_location}'
        f'/next24hours?unitGroup=metric&elements=datetimeEpoch%2Clatitude%2Clongitude%2C'
        f'tempmax%2Ctempmin%2Ctemp%2Cfeelslikemax%2Cfeelslikemin%2Cfeelslike%2Chumidity%2Cprecip%2Cpreciptype%2C'
        f'snow%2Cpressure%2Ccloudcover%2Cuvindex%2Csunrise%2Csunset%2Cmoonphase%2Cconditions%2Cdescription%2Cicon'

fetch_weather/templates/fetch_weather/about.html
{% extends "fetch_weather/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

fetch_weather/templates/fetch_weather/home.html
{% extends "fetch_weather/base.html" %}
{% block content %}
<div class="toast-container position-fixed bottom-0 start-0 p-3" id="toast-box">
</div>

<div class="container-fluid">
<div class="row g-3 justify-content-center">
    <div class="col-12 col-sm-4 col-xxl-4">
            <div class="form-floating">
                <input type="text" class="form-control" id="location" name="location">
                <label for="location">Location</label>
            </div>
    </div>
    <div class="col-12 col-sm-2 col-xxl-2">
        <div class="form-floating" id="units">
            {% if user.is_authenticated %}
            {% if user.userpreferences_set.first.units == 'metric' %}
            <select class="form-select"  hx-get="units" hx-target="#card-temp, #units" name="units" hx-trigger="change">
                <option selected value="metric" style="font-weight: bold;">Metric (°C, km)</option>
                <option value="us">US (°F, miles)</option>
                <option value="uk">UK (°C, miles)</option>
            </select>
            {% elif user.userpreferences_set.first.units == 'us' %}
            <select class="form-select" hx-get="units" hx-target="#card-temp, #units" name="units" hx-trigger="change">
                <option selected value="us" style="font-weight: bold;">US (°F, miles)</option>
                <option value="metric">Metric (°C, km)</option>
                <option value="uk">UK (°C, miles)</option>
            </select>
            {% elif user.userpreferences_set.first.units == 'uk' %}
            <select class="form-select" hx-get="units" hx-target="#card-temp, #units" name="units" hx-trigger="change">
                <option selected value="uk" style="font-weight: bold;">UK (°C, miles)</option>
                <option value="us">US (°F, miles)</option>
                <option value="metric">Metric (°C, km)</option>
            </select>
            {% endif %}
            {% else %}
                {% if request.session.units == 'metric' %}
                <select class="form-select"  hx-get="units" hx-target="#card-temp, #units" name="units" hx-trigger="change">
                    <option selected value="metric" style="font-weight: bold;">Metric (°C, km)</option>
                    <option value="us">US (°F, miles)</option>
                    <option value="uk">UK (°C, miles)</option>
                </select>
                {% elif request.session.units == 'us' %}
                <select class="form-select" hx-get="units" hx-target="#card-temp, #units" name="units" hx-trigger="change">
                    <option selected value="us" style="font-weight: bold;">US (°F, miles)</option>
                    <option value="metric">Metric (°C, km)</option>
                    <option value="uk">UK (°C, miles)</option>
                </select>
                {% elif request.session.units == 'uk' %}
                <select class="form-select" hx-get="units" hx-target="#card-temp, #units" name="units" hx-trigger="change">
                    <option selected value="uk" style="font-weight: bold;">UK (°C, miles)</option>
                    <option value="us">US (°F, miles)</option>
                    <option value="metric">Metric (°C, km)</option>
                </select>
                {% else %}
                <select class="form-select"  hx-get="units" hx-target="#card-temp, #units" name="units" hx-trigger="change">
                    <option selected value="metric" style="font-weight: bold;">Metric (°C, km)</option>
                    <option value="us">US (°F, miles)</option>
                    <option value="uk">UK (°C, miles)</option>
                </select>
                {% endif %}
            {% endif %}
            <label for="units">Units</label>
        </div>
    </div>
</div>
<div class="row justify-content-xxl-center">
    <div class="col-6 mt-2">
        <button class="btn btn-primary mb-4" id="loc_btn" hx-post="add_card/" hx-swap="beforeend" hx-target="#card-temp" hx-include="#location">Add location</button>
    </div>
</div>
<div class="row sortable" id="card-temp" hx-swap-oob="beforeend" hx-trigger="end" hx-swap="none" hx-post="/sort/" hx-target="#card-temp" hx-include="#card-order, #card-temp">
    {% for key, val in saved_locs.items %}
        <div class="col-12 col-md-6 col-xl-4 col-xxl-3" id="col_{{ val.pretty_loc }}">
            <input type="hidden" id="card-order" name="card-order" value="{{ key }}"/>
            <div class="card mb-4" id="{{ key }}">
                <svg xmlns="http://www.w3.org/2000/svg" id="handle" width="20" height="20" fill="currentColor" class="bi bi-arrows-move position-absolute top-0 start-0" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M7.646.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 1.707V5.5a.5.5 0 0 1-1 0V1.707L6.354 2.854a.5.5 0 1 1-.708-.708l2-2zM8 10a.5.5 0 0 1 .5.5v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 14.293V10.5A.5.5 0 0 1 8 10zM.146 8.354a.5.5 0 0 1 0-.708l2-2a.5.5 0 1 1 .708.708L1.707 7.5H5.5a.5.5 0 0 1 0 1H1.707l1.147 1.146a.5.5 0 0 1-.708.708l-2-2zM10 8a.5.5 0 0 1 .5-.5h3.793l-1.147-1.146a.5.5 0 0 1 .708-.708l2 2a.5.5 0 0 1 0 .708l-2 2a.5.5 0 0 1-.708-.708L14.293 8.5H10.5A.5.5 0 0 1 10 8z"/>
                  </svg>
                <div class="row justify-content-center">
                    <div class="col-6 d-flex justify-content-center col-xxl-4 pt-2">
                        <img src=https://raw.githubusercontent.com/visualcrossing/WeatherIcons/main/SVG/1st%20Set%20-%20Color/{{ val.icon }}.svg class="card-img mx-auto" id="icon_{{ val.pretty_loc }}" style="margin-bottom: 5px; aspect-ratio: 1;"/>
                    </div>
                    <div class="col-xxl-8">
                        <button type="button" id="remove-btn" data-bs-toggle="tooltip" data-bs-title="Remove" class="btn-close remove position-absolute top-0 end-0" hx-params="{{key}}" hx-post="remove_card/" hx-swap="none" hx-select-oob="#toast-box" hx-trigger="click consume delay:0.9s"></button> 
                        <div class="col-11">
                        <h5 class="card-title ms-2" style="font-weight: bold;">{{ key }}</h5></div>
                        <div class="row">
                            <div class="col-5 col-xxl-4">
                                <h5 class="card-subtitle mb-2 text-muted ms-2" id="{{val.pretty_loc}}_fronttemp">{{ val.temp }}{{ front_units.temp_unit }}</h5>
                            </div>
                            <div class="col-7 col-xxl-8">
                                <h5 class="card-subtitle mb-2 me-2 text-muted" id="{{val.pretty_loc}}_conditions">{{ val.conditions }}</h5>
                            </div>
                            <div class="row" style="margin-bottom: 10px;">
                                <div class="col-12 ms-2 me-1" id="{{val.pretty_loc}}_description">
                                    {{ val.daily_description }}
                                </div>
                            </div>
                        </div>
                </div>
                </div>
                <div class="row">
                    <div class="col d-flex justify-content-center">
                        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#detailed_{{val.pretty_loc}}" aria-expanded="false">
                            More Details
                        </button>
                    </div>
                    <div class="col d-flex justify-content-center me-1">
                        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#hr_{{val.pretty_loc}}" aria-expanded="false">
                            24-hr Forecast
                        </button>
                    </div>
                </div>
                <div class="row pt-2">
                    <div class="collapse" id="detailed_{{val.pretty_loc}}">
                        <div class="card-body">
                            <table class="table table-sm table-hover" id="{{val.pretty_loc}}_table">
                                <tr>
                                    <th scope="row">Data From</th>
                                    <td class="text-end" id="{{val.pretty_loc}}_datetime"><script>
                                        var new_date = new Date("{{ val.tz_display_dt }}")
                                        document.querySelector("#{{val.pretty_loc}}_datetime").textContent = new_date.toLocaleString(undefined, {dateStyle: "medium", timeStyle: "short"})
                                    </script></td>
                                </tr>
                                <tr>
                                    <th scope="row">Feels Like</th>
                                    <td class="text-end">{{val.feelslike}}{{front_units.temp_unit}}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Humidity</th>
                                    <td class="text-end">{{val.humidity}}%</td>
                                </tr>
                                <tr>
                                    <th scope="row">Precipitation Amount</th>
                                    <td class="text-end">{{val.precip}} {{front_units.precip_unit}}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Snow</th>
                                    <td class="text-end">{{val.snow}} {{front_units.snow_unit}}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Pressure</th>
                                    <td class="text-end">{{val.pressure}} {{front_units.pressure_unit}}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Cloud Cover</th>
                                    <td class="text-end">{{val.cloudcover}}%</td>
                                </tr>
                                <tr>
                                    <th scope="row">UV Index</th>
                                    <td class="text-end">{{val.uvindex}}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Sunrise</th>
                                    <td class="text-end" id="{{val.pretty_loc}}_sunrise"><script>
                                        var new_date = new Date("{{ val.sunrise }}")
                                        document.querySelector("#{{val.pretty_loc}}_sunrise").textContent = new_date.toLocaleTimeString(undefined, {timeStyle: "short"})
                                    </script></td>
                                </tr>
                                <tr>
                                    <th scope="row">Sunset</th>
                                    <td class="text-end" id="{{val.pretty_loc}}_sunset"><script>
                                        var new_date = new Date("{{ val.sunset }}")
                                        document.querySelector("#{{val.pretty_loc}}_sunset").textContent = new_date.toLocaleTimeString(undefined, {timeStyle: "short"})
                                    </script></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="collapse" id="hr_{{val.pretty_loc}}">
                        <div class="col">
                            <div class="card card-body">
                                24 hr outlook here
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <small class="text-muted" id="{{val.pretty_loc}}_last_updated"><script>
                        var new_date = new Date("{{ val.tz_display_lm }}")
                        document.querySelector("#{{val.pretty_loc}}_last_updated").textContent = "Last updated " + new_date.toLocaleString(undefined, {dateStyle:"medium", timeStyle:"short"})
                    </script></small>
                    <svg xmlns="http://www.w3.org/2000/svg" id="update_btn" hx-post="update_card/" hx-target="#col_{{ val.pretty_loc }}" hx-params="{{ val.loc }}" width="16" height="16" fill="currentColor" class="bi bi-arrow-clockwise" data-bs-toggle="tooltip" data-bs-title="Update" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
                        <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
                      </svg>
                </div>
            </div>
            
        </div>
        {% endfor %}
    </div>
</div>


<!-- <input type="time"> -->
{% endblock %}

fetch_weather/templates/fetch_weather/new_home.html
{% extends "fetch_weather/base.html" %}
{% block content %}
<div class="container" style="max-width: 90%;">
    <div class="row justify-content-center mb-5">
        <div class="col-auto">
            <form method="POST">
                {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="location" size="60">
                <label for="location">Location</label>
            </div>
            <div class="col-auto d-flex align-items-center">
                <button class="btn btn-primary" type="submit">Add location</button>
            </div>
            </form>
            <div class="col-auto">
                <div class="form-floating">
                    <select class="form-select" hx-get="units" hx-target="#test" name="units">
                    <option selected value="metric">Metric (°C, km)</option>
                    <option value="us">US (°F, miles)</option>
                    <option value="uk">UK (°C, miles)</option>
                    </select>
                    <label for="units">Units (Currently Using: {% if user.userpreferences_set.first.units == 'us' %}{{ units.us }})
                        {% elif user.userpreferences_set.first.units == 'metric' %}{{ units.metric }})
                        {% elif user.userpreferences_set.first.units == 'uk' %}{{ units.uk }})</label>{% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container" style="max-width: 90%;" id="test">
    <div class="row">
    {% for key, val in saved_locs.items %}
    {{icons}}
    <div class="col-sm-3">
    <div class="card mb-4">
        <div class="row no-gutters" style="margin-left: 5px;">
            <div class="col-md-4" style="height: max-content;">
                <img src=https://raw.githubusercontent.com/visualcrossing/WeatherIcons/main/SVG/1st%20Set%20-%20Color/{{ val3.icon }}.svg class="card-img" style="margin-bottom: 10px; aspect-ratio: 1;">
            </div>
            <div class="col-md-8">
                <h5 class="card-title" style="font-weight: bold;">{{ key }}</h5>
                <div class="row no-gutters">
                    <div class="col-auto">
                        <h5 class="card-subtitle mb-2 text-muted">{{ val.temp }}{{ selected_unit }}</h5>
                    </div>
                    <div class="col-auto">
                    <h5 class="card-subtitle mb-2 text-muted">{{ val.conditions }}</h5>
                    </div>
                    <div class="row" style="margin-bottom: 10px;">
                        <div class="col-auto">
                            {{ val.description }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row d-flex mt-auto">
            <div class="col d-flex justify-content-end" style="width: 50%;">
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target=#detailed_{{ key }} aria-expanded="false">
                More Details
                </button>
            </div>
            <div class="col d-flex justify-content-start" style="width: 50%;">
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target=#24hr_{{ key }}aria-expanded="false">
                24-hr Forecast
                </button>
            </div>
        </div>
        <div class="row no-gutters pt-2">
            <div class="collapse" id=detailed_{{ key }}>
                <div class="card-body">
                    <table class="table table-sm table-hover">
                        {% for key2, val2 in val.items %}
                        <tr>
                            <th scope="row">{{ key2 }}</th>
                            <td class="text-end">{{ val2 }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="collapse" id=24hr_{{ key }}>
                <div class="col">
                    <div class="card card-body">
                    24 hr outlook here
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% endfor %}
</div>
</div>

{% endblock content %}

fetch_weather/templates/fetch_weather/past.html
{% extends "fetch_weather/base.html" %}
{% block content %}
<select class="form-select" aria-label="Default select example">
    <option selected>Celsius</option>
    <option value="1">Fahrenheit</option>
<input type="date", max="{% now 'Y-m-d' %}">
{% endblock content %}